openapi: 3.0.0
servers:
  - url: //metamdb.tu-bs.de/api
    description: MetAMDB server

info:
  description: |
    This is the MetAMDB Api Documentation.
  version: 1.0.0
  title: MetAMDB Api Documentation

tags:
  - name: reactions
    description: Everything about reactions.
  - name: pathways
    description: Everything about pathways.
  - name: search
    description: Search operations.

x-tagGroups:
  - name: General
    tags:
      - reactions
      - pathways
      - search

paths:
  "/reactions":
    get:
      tags:
        - reactions
      summary: Get reactions
      description: |
        On success, the HTTP status code in the response header is `200` OK and the response body contains an object whose key is `"reactions"` and whose value is an array of reaction objects in JSON format.

        Objects are returned in the order requested. If an object is not found, a `null` value is returned in the appropriate position. Duplicate `ids` in the query will result in duplicate objects in the response. On error, the header status code is an error code and the response body contains an error object.
      operationId: getReactionsById
      parameters:
        - name: ids
          in: query
          description: A comma-separated list of MetAMDB reaction ids.
          schema:
            type: array
            items:
              type: integer
              format: int64
          required: true
          examples:
            one-id:
              value: 1
            two-ids:
              value: 1,2
      responses:
        "200":
          $ref: "#/components/responses/Reactions"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/reactions/{id}":
    get:
      tags:
        - reactions
      summary: Find reaction by ID
      description: Returns a single reaction for the specified MetAMDB reaction ID.
      operationId: getReactionById
      parameters:
        - name: id
          in: path
          description: MetAMDB ID of reaction to return.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          $ref: "#/components/responses/Reaction"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/pathways":
    get:
      tags:
        - pathways
      summary: Get pathways
      description: |
        On success, the HTTP status code in the response header is `200` OK and the response body contains an object whose key is `"pathways"` and whose value is an array of pathway objects in JSON format.

        Objects are returned in the order requested. If an object is not found, a `null` value is returned in the appropriate position. Duplicate `ids` in the query will result in duplicate objects in the response. On error, the header status code is an error code and the response body contains an error object.
      operationId: getPathwaysById
      parameters:
        - name: ids
          in: query
          description: A comma-separated list of MetAMDB pathway ids.
          schema:
            type: array
            items:
              type: integer
              format: int64
          required: true
          examples:
            one-id:
              value: 1
            two-ids:
              value: 1,2
      responses:
        "200":
          $ref: "#/components/responses/Pathways"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  "/pathways/{id}":
    get:
      tags:
        - pathways
      summary: Find pathway by ID
      description: Returns a single pathway object for the specified MetAMDB pathway ID.
      operationId: getPathwayById
      parameters:
        - name: id
          in: path
          description: MetAMDB ID of pathway to return.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          $ref: "#/components/responses/Pathway"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /search:
    get:
      tags:
        - search
      summary: Search for an item
      description: |
        Search for MetAMDB reactions of pathways that match a keyword string.

        **Encode spaces** with the hex code `%20`.

        **Field filters:** By default, results are returned when a match is found in any field of the target object type. Searches can be made more specific by specifying a `name` or `source`.

        For example: The query `q=name:1500%20source:kegg&type=reaction` returns only reactions with the identifier "1500" from the source "kegg".
      operationId: getSearch
      parameters:
        - name: q
          in: path
          description: Search query keywords and optional field filters.
          required: true
          schema:
            type: string
        - name: type
          in: path
          description: |
            Item types to seach across. 

            Valid types are: `reaction`, and `pathway`.
          required: true
          schema:
            type: string
        - name: limit
          in: path
          required: false
          schema:
            type: integer
            format: int64
            minimum: 1
            maximum: 50
          default: 20
          description: Maximum number of results to return.
        - name: offset
          in: path
          required: false
          schema:
            type: integer
            format: int64
          default: 0
          description: The index of the first result to return.

      responses:
        "200":
          $ref: "#/components/responses/Search"
        "400":
          description: Bad query supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  responses:
    Pathway:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pathway"
          examples:
            /pathways/2:
              $ref: "#/components/examples/pathway-two"
            /pathways/5:
              $ref: "#/components/examples/pathway-10"
    Pathways:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pathways"
          examples:
            /pathways?ids=2:
              $ref: "#/components/examples/pathways-one-value"
            /pathways?ids=2,5:
              $ref: "#/components/examples/pathways-two-value"
            /pathways?ids=2,abc:
              $ref: "#/components/examples/pathways-one-value-one-bad"
    Reaction:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Reaction"
          examples:
            /reactions/2:
              $ref: "#/components/examples/reaction-two"
            /reactions/1916:
              $ref: "#/components/examples/reaction-1916"
    Reactions:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Reactions"
          examples:
            /reactions?ids=2:
              $ref: "#/components/examples/reactions-one-value"
            /reactions?ids=2,1916:
              $ref: "#/components/examples/reactions-two-value"
            /reactions?ids=2,abc:
              $ref: "#/components/examples/reactions-one-value-one-bad"

    Search:
      description: Successful operation
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/PathwaySearch"
              - $ref: "#/components/schemas/ReactionSearch"
  examples:
    pathways-one-value:
      value:
        pathways:
          - externalUrls:
              metamdb: https://metamdb.tu-bs.de/pathway/2
            href: https://metamdb.tu-bs.de/api/pathways/2
            id: 2
            name: protocatechuate degradation II (ortho-cleavage pathway)
            reactions:
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/55.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/55
                formula: H2O + (4,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-oxoadipate
                href: https://metamdb.tu-bs.de/api/reactions/55
                id: 55
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR11711
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R02991
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 3-OXOADIPATE-ENOL-LACTONASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     55\n\n  2  1\n$MOL\n{\"n\": \"5-oxo-4,5-dihydrofuran 2-acetate\", \"i\": 6444, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:40:21
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/416.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/416
                formula: (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/416
                id: 416
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR260
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR263
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03307
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03308
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 5.5.1.2-RXN
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: CARBOXY-CISCIS-MUCONATE-CYCLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     416\n\n  1  1\n$MOL\n{\"n\": \"2-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 23805, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: false
                updatedBy: null
                updatedOn: 2020-04-08T14:23:24
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/835.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/835
                formula: H+ + (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = CO2 + (4,5-dihydro-5-oxofuran-2-yl)-acetate
                href: https://metamdb.tu-bs.de/api/reactions/835
                id: 835
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR3361
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BS18492
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03470
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 4-CARBOXYMUCONOLACTONE-DECARBOXYLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     835\n\n  1  2\n$MOL\n{\"n\": \"3-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 2299, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-29T12:49:47
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/1286.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/1286
                formula: oxygen + protocatechuate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/1286
                id: 1286
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR40477
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R01631
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: PROTOCATECHUATE-34-DIOXYGENASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     1286\n\n  2  1\n$MOL\n{\"n\": \"O2\", \"i\": 16619, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:21:47
            source: metacyc
            sourceId: PROTOCATECHUATE-ORTHO-CLEAVAGE-PWY
            type: pathway
    pathways-two-value:
      value:
        pathways:
          - externalUrls:
              metamdb: https://metamdb.tu-bs.de/pathway/2
            href: https://metamdb.tu-bs.de/api/pathways/2
            id: 2
            name: protocatechuate degradation II (ortho-cleavage pathway)
            reactions:
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/55.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/55
                formula: H2O + (4,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-oxoadipate
                href: https://metamdb.tu-bs.de/api/reactions/55
                id: 55
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR11711
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R02991
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 3-OXOADIPATE-ENOL-LACTONASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     55\n\n  2  1\n$MOL\n{\"n\": \"5-oxo-4,5-dihydrofuran 2-acetate\", \"i\": 6444, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:40:21
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/416.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/416
                formula: (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/416
                id: 416
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR260
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR263
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03307
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03308
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 5.5.1.2-RXN
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: CARBOXY-CISCIS-MUCONATE-CYCLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     416\n\n  1  1\n$MOL\n{\"n\": \"2-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 23805, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: false
                updatedBy: null
                updatedOn: 2020-04-08T14:23:24
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/835.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/835
                formula: H+ + (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = CO2 + (4,5-dihydro-5-oxofuran-2-yl)-acetate
                href: https://metamdb.tu-bs.de/api/reactions/835
                id: 835
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR3361
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BS18492
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03470
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 4-CARBOXYMUCONOLACTONE-DECARBOXYLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     835\n\n  1  2\n$MOL\n{\"n\": \"3-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 2299, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-29T12:49:47
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/1286.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/1286
                formula: oxygen + protocatechuate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/1286
                id: 1286
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR40477
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R01631
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: PROTOCATECHUATE-34-DIOXYGENASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     1286\n\n  2  1\n$MOL\n{\"n\": \"O2\", \"i\": 16619, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:21:47
            source: metacyc
            sourceId: PROTOCATECHUATE-ORTHO-CLEAVAGE-PWY
            type: pathway
          - externalUrls:
              metamdb: https://metamdb.tu-bs.de/pathway/5
            href: https://metamdb.tu-bs.de/api/pathways/5
            id: 5
            name: flavin biosynthesis IV (mammalian)
            reactions:
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/1878.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/1878
                formula: riboflavin + ATP = FMN + ADP + H+
                href: https://metamdb.tu-bs.de/api/reactions/1878
                id: 1878
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR47765
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R00549
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: RIBOFLAVINKIN-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     1878\n\n  2  2\n$MOL\n{\"n\": \"ATP\", \"i\": 22420, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-05-25T15:26:18
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/1960.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/1960
                formula: FMN + ATP + H+ = FAD + diphosphate
                href: https://metamdb.tu-bs.de/api/reactions/1960
                id: 1960
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR47867
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R00161
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: FADSYN-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     1960\n\n  2  2\n$MOL\n{\"n\": \"ATP\", \"i\": 22420, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-08-11T10:50:35
            source: metacyc
            sourceId: PWY66-366
            type: pathway
    pathway-two:
      value:
        externalUrls:
          metamdb: https://metamdb.tu-bs.de/pathway/2
        href: https://metamdb.tu-bs.de/api/pathways/2
        id: 2
        name: protocatechuate degradation II (ortho-cleavage pathway)
        reactions:
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/55.svg
              metamdb: https://metamdb.tu-bs.de/reaction/55
            formula: H2O + (4,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-oxoadipate
            href: https://metamdb.tu-bs.de/api/reactions/55
            id: 55
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR11711
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R02991
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: 3-OXOADIPATE-ENOL-LACTONASE-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     55\n\n  2  1\n$MOL\n{\"n\": \"5-oxo-4,5-dihydrofuran 2-acetate\", \"i\": 6444, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy: 1
            updatedOn: 2020-04-08T14:40:21
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/416.svg
              metamdb: https://metamdb.tu-bs.de/reaction/416
            formula: (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-carboxy-cis,cis-muconate
            href: https://metamdb.tu-bs.de/api/reactions/416
            id: 416
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR260
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR263
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R03307
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R03308
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: 5.5.1.2-RXN
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: CARBOXY-CISCIS-MUCONATE-CYCLASE-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     416\n\n  1  1\n$MOL\n{\"n\": \"2-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 23805, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: false
            updatedBy: null
            updatedOn: 2020-04-08T14:23:24
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/835.svg
              metamdb: https://metamdb.tu-bs.de/reaction/835
            formula: H+ + (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = CO2 + (4,5-dihydro-5-oxofuran-2-yl)-acetate
            href: https://metamdb.tu-bs.de/api/reactions/835
            id: 835
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR3361
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BS18492
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R03470
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: 4-CARBOXYMUCONOLACTONE-DECARBOXYLASE-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     835\n\n  1  2\n$MOL\n{\"n\": \"3-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 2299, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy: 1
            updatedOn: 2020-04-29T12:49:47
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/1286.svg
              metamdb: https://metamdb.tu-bs.de/reaction/1286
            formula: oxygen + protocatechuate = H+ + 3-carboxy-cis,cis-muconate
            href: https://metamdb.tu-bs.de/api/reactions/1286
            id: 1286
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR40477
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R01631
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: PROTOCATECHUATE-34-DIOXYGENASE-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     1286\n\n  2  1\n$MOL\n{\"n\": \"O2\", \"i\": 16619, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy: 1
            updatedOn: 2020-04-08T14:21:47
        source: metacyc
        sourceId: PROTOCATECHUATE-ORTHO-CLEAVAGE-PWY
        type: pathway
    pathway-10:
      value:
        externalUrls:
          metamdb: https://metamdb.tu-bs.de/pathway/5
        href: https://metamdb.tu-bs.de/api/pathways/5
        id: 5
        name: flavin biosynthesis IV (mammalian)
        reactions:
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/1878.svg
              metamdb: https://metamdb.tu-bs.de/reaction/1878
            formula: riboflavin + ATP = FMN + ADP + H+
            href: https://metamdb.tu-bs.de/api/reactions/1878
            id: 1878
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR47765
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R00549
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: RIBOFLAVINKIN-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     1878\n\n  2  2\n$MOL\n{\"n\": \"ATP\", \"i\": 22420, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy: 1
            updatedOn: 2020-05-25T15:26:18
          - externalUrls:
              img: https://metamdb.tu-bs.de/img/aam/1960.svg
              metamdb: https://metamdb.tu-bs.de/reaction/1960
            formula: FMN + ATP + H+ = FAD + diphosphate
            href: https://metamdb.tu-bs.de/api/reactions/1960
            id: 1960
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR47867
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R00161
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: FADSYN-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     1960\n\n  2  2\n$MOL\n{\"n\": \"ATP\", \"i\": 22420, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy: 1
            updatedOn: 2020-08-11T10:50:35
        source: metacyc
        sourceId: PWY66-366
        type: pathway
    pathways-one-value-one-bad:
      value:
        pathways:
          - externalUrls:
              metamdb: https://metamdb.tu-bs.de/pathway/2
            href: https://metamdb.tu-bs.de/api/pathways/2
            id: 2
            name: protocatechuate degradation II (ortho-cleavage pathway)
            reactions:
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/55.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/55
                formula: H2O + (4,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-oxoadipate
                href: https://metamdb.tu-bs.de/api/reactions/55
                id: 55
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR11711
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R02991
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 3-OXOADIPATE-ENOL-LACTONASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     55\n\n  2  1\n$MOL\n{\"n\": \"5-oxo-4,5-dihydrofuran 2-acetate\", \"i\": 6444, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:40:21
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/416.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/416
                formula: (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/416
                id: 416
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR260
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR263
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03307
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03308
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 5.5.1.2-RXN
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: CARBOXY-CISCIS-MUCONATE-CYCLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     416\n\n  1  1\n$MOL\n{\"n\": \"2-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 23805, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: false
                updatedBy: null
                updatedOn: 2020-04-08T14:23:24
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/835.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/835
                formula: H+ + (2-carboxy-2,5-dihydro-5-oxofuran-2-yl)-acetate = CO2 + (4,5-dihydro-5-oxofuran-2-yl)-acetate
                href: https://metamdb.tu-bs.de/api/reactions/835
                id: 835
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR3361
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BS18492
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R03470
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: 4-CARBOXYMUCONOLACTONE-DECARBOXYLASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     835\n\n  1  2\n$MOL\n{\"n\": \"3-carboxy-2,5-dihydro-5-oxofuran-2-aceta\", \"i\": 2299, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-29T12:49:47
              - externalUrls:
                  img: https://metamdb.tu-bs.de/img/aam/1286.svg
                  metamdb: https://metamdb.tu-bs.de/reaction/1286
                formula: oxygen + protocatechuate = H+ + 3-carboxy-cis,cis-muconate
                href: https://metamdb.tu-bs.de/api/reactions/1286
                id: 1286
                identifiers:
                  - source:
                      id: 1
                      name: BRENDA
                    databaseIdentifier: BR40477
                  - source:
                      id: 2
                      name: KEGG
                    databaseIdentifier: R01631
                  - source:
                      id: 3
                      name: MetaCyc
                    databaseIdentifier: PROTOCATECHUATE-34-DIOXYGENASE-RXN
                rxnFile: "$RXN\n\n  EC-BLAST     1286\n\n  2  1\n$MOL\n{\"n\": \"O2\", \"i\": 16619, \"r\": \"s\", \"p\": 1}\n..."
                type: reaction
                updated: true
                updatedBy: 1
                updatedOn: 2020-04-08T14:21:47
            source: metacyc
            sourceId: PROTOCATECHUATE-ORTHO-CLEAVAGE-PWY
            type: pathway
          - null
    reaction-1916:
      value:
        compounds:
          - compound:
              id: 9251
              name: phosphate
            position: 3
            quantity: 1
            reactant: product
          - compound:
              id: 45724
              name: D-fructose 6-phosphate
            position: 2
            quantity: 1
            reactant: substrate
          - compound:
              id: 60639
              name: D-fructose 1,6-bisphosphate
            position: 4
            quantity: 1
            reactant: product
          - compound:
              id: 75289
              name: diphosphate
            position: 1
            quantity: 1
            reactant: substrate
        externalUrls:
          metamdb: "https://metamdb.tu-bs.de/reaction/1916"
          img: "https://metamdb.tu-bs.de/img/aam/1916.svg"
        formula: "beta-D-fructofuranose 6-phosphate + diphosphate = H+ + phosphate + beta-D-fructose 1,6-bisphosphate"
        href: "https://metamdb.tu-bs.de/api/reactions/1916"
        id: 1916
        identifiers:
          - source:
              id: 1
              name: BRENDA
            databaseIdentifier: BR47815
          - source:
              id: 2
              name: KEGG
            databaseIdentifier: R00764
          - source:
              id: 2
              name: KEGG
            databaseIdentifier: R02073
          - source:
              id: 3
              name: MetaCyc
            databaseIdentifier: 2.7.1.90-RXN
        rxnFile: "$RXN\n\n  EC-BLAST     1916\n\n  2  2\n$MOL\n{\"n\": \"D-fructose 6-phosphate\", \"i\": 45724, \"r\": \"s\", \"p\": 0}\n..."
        type: reaction
        updated: true
        updatedBy:
          id: 1
          name: Collin
          orcid: 0000-0002-2938-9940
        updatedOn: 2021-10-19T15:40:44
    reaction-two:
      value:
        compounds:
          - compound:
              id: 10213
              name: (R)-pantoate
            position: 2
            quantity: 1
            reactant: substrate
          - compound:
              id: 10215
              name: (R)-pantothenate
            position: 6
            quantity: 1
            reactant: product
          - compound:
              id: 22420
              name: ATP
            position: 1
            quantity: 1
            reactant: substrate
          - compound:
              id: 31197
              name: beta-Alanine
            position: 3
            quantity: 1
            reactant: substrate
          - compound:
              id: 31336
              name: AMP
            position: 4
            quantity: 1
            reactant: product
          - compound:
              id: 75289
              name: diphosphate
            position: 5
            quantity: 1
            reactant: product
        externalUrls:
          metamdb: "https://metamdb.tu-bs.de/reaction/2"
          img: "https://metamdb.tu-bs.de/img/aam/2.svg"
        formula: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
        href: "https://metamdb.tu-bs.de/api/reactions/2"
        id: 2
        identifiers:
          - source:
              id: 1
              name: BRENDA
            databaseIdentifier: BR101
          - source:
              id: 2
              name: KEGG
            databaseIdentifier: R02473
          - source:
              id: 3
              name: MetaCyc
            databaseIdentifier: PANTOATE-BETA-ALANINE-LIG-RXN
        rxnFile: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
        type: reaction
        updated: true
        updatedBy:
          id: 1
          name: Collin
          orcid: 0000-0002-2938-9940
        updatedOn: 2020-05-11T12:43:17
    reactions-one-value:
      value:
        reactions:
          - compounds:
              - compound:
                  id: 10213
                  name: (R)-pantoate
                position: 2
                quantity: 1
                reactant: substrate
              - compound:
                  id: 10215
                  name: (R)-pantothenate
                position: 6
                quantity: 1
                reactant: product
              - compound:
                  id: 22420
                  name: ATP
                position: 1
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31197
                  name: beta-Alanine
                position: 3
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31336
                  name: AMP
                position: 4
                quantity: 1
                reactant: product
              - compound:
                  id: 75289
                  name: diphosphate
                position: 5
                quantity: 1
                reactant: product
            externalUrls:
              metamdb: "https://metamdb.tu-bs.de/reaction/2"
              img: "https://metamdb.tu-bs.de/img/aam/2.svg"
            formula: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
            href: "https://metamdb.tu-bs.de/api/reactions/2"
            id: 2
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR101
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R02473
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: PANTOATE-BETA-ALANINE-LIG-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy:
              id: 1
              name: Collin
              orcid: 0000-0002-2938-9940
            updatedOn: 2020-05-11T12:43:17
    reactions-two-value:
      value:
        reactions:
          - compounds:
              - compound:
                  id: 10213
                  name: (R)-pantoate
                position: 2
                quantity: 1
                reactant: substrate
              - compound:
                  id: 10215
                  name: (R)-pantothenate
                position: 6
                quantity: 1
                reactant: product
              - compound:
                  id: 22420
                  name: ATP
                position: 1
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31197
                  name: beta-Alanine
                position: 3
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31336
                  name: AMP
                position: 4
                quantity: 1
                reactant: product
              - compound:
                  id: 75289
                  name: diphosphate
                position: 5
                quantity: 1
                reactant: product
            externalUrls:
              metamdb: "https://metamdb.tu-bs.de/reaction/2"
              img: "https://metamdb.tu-bs.de/img/aam/2.svg"
            formula: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
            href: "https://metamdb.tu-bs.de/api/reactions/2"
            id: 2
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR101
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R02473
              - source:
                  id: 3
                  name: MetaCyc
            rxnFile: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy:
              id: 1
              name: Collin
              orcid: 0000-0002-2938-9940
            updatedOn: 2020-05-11T12:43:17
          - compounds:
              - compound:
                  id: 9251
                  name: phosphate
                position: 3
                quantity: 1
                reactant: product
              - compound:
                  id: 45724
                  name: D-fructose 6-phosphate
                position: 2
                quantity: 1
                reactant: substrate
              - compound:
                  id: 60639
                  name: D-fructose 1,6-bisphosphate
                position: 4
                quantity: 1
                reactant: product
              - compound:
                  id: 75289
                  name: diphosphate
                position: 1
                quantity: 1
                reactant: substrate
            externalUrls:
              metamdb: "https://metamdb.tu-bs.de/reaction/1916"
              img: "https://metamdb.tu-bs.de/img/aam/1916.svg"
            formula: "beta-D-fructofuranose 6-phosphate + diphosphate = H+ + phosphate + beta-D-fructose 1,6-bisphosphate"
            href: "https://metamdb.tu-bs.de/api/reactions/1916"
            id: 1916
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR47815
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R00764
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R02073
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: 2.7.1.90-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     1916\n\n  2  2\n$MOL\n{\"n\": \"D-fructose 6-phosphate\", \"i\": 45724, \"r\": \"s\", \"p\": 0}\n..."
            type: reaction
            updated: true
            updatedBy:
              id: 1
              name: Collin
              orcid: 0000-0002-2938-9940
            updatedOn: 2021-10-19T15:40:44
    reactions-one-value-one-bad:
      value:
        reactions:
          - compounds:
              - compound:
                  id: 10213
                  name: (R)-pantoate
                position: 2
                quantity: 1
                reactant: substrate
              - compound:
                  id: 10215
                  name: (R)-pantothenate
                position: 6
                quantity: 1
                reactant: product
              - compound:
                  id: 22420
                  name: ATP
                position: 1
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31197
                  name: beta-Alanine
                position: 3
                quantity: 1
                reactant: substrate
              - compound:
                  id: 31336
                  name: AMP
                position: 4
                quantity: 1
                reactant: product
              - compound:
                  id: 75289
                  name: diphosphate
                position: 5
                quantity: 1
                reactant: product
            externalUrls:
              metamdb: "https://metamdb.tu-bs.de/reaction/2"
              img: "https://metamdb.tu-bs.de/img/aam/2.svg"
            formula: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
            href: "https://metamdb.tu-bs.de/api/reactions/2"
            id: 2
            identifiers:
              - source:
                  id: 1
                  name: BRENDA
                databaseIdentifier: BR101
              - source:
                  id: 2
                  name: KEGG
                databaseIdentifier: R02473
              - source:
                  id: 3
                  name: MetaCyc
                databaseIdentifier: PANTOATE-BETA-ALANINE-LIG-RXN
            rxnFile: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
            type: reaction
            updated: true
            updatedBy:
              id: 1
              name: Collin
              orcid: 0000-0002-2938-9940
            updatedOn: 2020-05-11T12:43:17
          - null
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: Invalid id
    PathwaySearch:
      description: Pathway search.
      type: object
      properties:
        pathways:
          type: object
          properties:
            href:
              type: string
              description: Link to api call
              example: "https://metamdb.tu-bs.de/api/search?q=source:brenda&type=pathway&offset=0&limit=20"
            items:
              type: array
              items:
                $ref: "#/components/schemas/Pathway"
            limit:
              type: integer
              format: int64
              example: 20
              description: Maximum number of results to return
            next:
              type: string
              description: Next search results based on offset and limit
              example: "https://metamdb.tu-bs.de/api/search?q=source:brenda&type=pathway&offset=20&limit=20"
            offset:
              type: integer
              format: int64
              example: 0
              description: The index of the first result to return
            previous:
              type: string
              description: Previous search results based on offset and limit
              example: null
            total:
              type: integer
              format: int64
              example: 166
              description: Total number of results
    ReactionSearch:
      description: Reaction search.
      type: object
      properties:
        reactions:
          type: object
          properties:
            href:
              type: string
              description: Link to api call
              example: "https://metamdb.tu-bs.de/api/search?q=source:brenda&type=reaction&offset=0&limit=20"
            items:
              type: array
              items:
                $ref: "#/components/schemas/Reaction"
            limit:
              type: integer
              format: int64
              example: 20
              description: Maximum number of results to return
            next:
              type: string
              description: Next search results based on offset and limit
              example: "https://metamdb.tu-bs.de/api/search?q=source:brenda&type=reaction&offset=20&limit=20"
            offset:
              type: integer
              format: int64
              example: 0
              description: The index of the first result to return
            previous:
              type: string
              description: Previous search results based on offset and limit
              example: null
            total:
              type: integer
              format: int64
              example: 61129
              description: Total number of results

    Pathways:
      type: object
      properties:
        pathways:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/Pathway"
    Pathway:
      description: A representation of a pathway
      type: object
      properties:
        externalUrls:
          type: object
          properties:
            metamdb:
              type: string
              description: Link to MetAMDB pathway
              example: "https://metamdb.tu-bs.de/pathway/2"
        href:
          type: string
          description: Link to api call
          example: "https://metamdb.tu-bs.de/api/pathways/2"
        id:
          type: integer
          format: int64
          example: 2
          description: Pathway ID
        name:
          type: string
          description: Name of the pathway
          example: "protocatechuate degradation II (ortho-cleavage pathway)"
        reactions:
          type: array
          items:
            type: object
            properties:
              reaction:
                type: object
                $ref: "#/components/schemas/PathwayReaction"
        source:
          type: string
          description: Database source of pathway
          example: metacyc
        sourceId:
          type: string
          description: ID of pathway in source database
          example: "PROTOCATECHUATE-ORTHO-CLEAVAGE-PWY"
        type:
          type: string
          default: pathway
          description: Type of return

    Reactions:
      description: An array of reactions
      type: object
      properties:
        reactions:
          type: array
          items:
            type: object
            $ref: "#/components/schemas/Reaction"
    Reaction:
      description: A representation of a reaction
      type: object
      properties:
        compounds:
          type: array
          example:
            - compound:
                id: 10213
                name: (R)-pantoate
              position: 2
              quantity: 1
              reactant: substrate
            - compound:
                id: 10215
                name: (R)-pantothenate
              position: 6
              quantity: 1
              reactant: product
            - compound:
                id: 22420
                name: ATP
              position: 1
              quantity: 1
              reactant: substrate
            - compound:
                id: 31197
                name: beta-Alanine
              position: 3
              quantity: 1
              reactant: substrate
            - compound:
                id: 31336
                name: AMP
              position: 4
              quantity: 1
              reactant: product
            - compound:
                id: 75289
                name: diphosphate
              position: 5
              quantity: 1
              reactant: product
          items:
            type: object
            properties:
              compound:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: ID of the compound
                  name:
                    type: string
                    description: Name of the compound
              position:
                type: integer
                format: int64
                description: Position of the compound in said reaction
              quantity:
                type: integer
                format: int64
                description: Quantity of the compound
              reactant:
                type: string
                enum: [substrate, product]
                description: Reactant status of compound for the reaction
        externalUrls:
          type: object
          properties:
            metamdb:
              type: string
              description: Link to MetAMDB reaction
              example: "https://metamdb.tu-bs.de/reaction/2"
            img:
              type: string
              description: Link to reaction image
              example: "https://metamdb.tu-bs.de/img/aam/2.svg"
        formula:
          type: string
          example: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
          description: Formula of the reaction
        href:
          type: string
          description: Link to api call
          example: "https://metamdb.tu-bs.de/api/reactions/2"
        id:
          type: integer
          format: int64
          example: 2
          description: Reaction ID
        identifiers:
          type: array
          example:
            - source:
                id: 1
                name: BRENDA
              databaseIdentifier: BR101
            - source:
                id: 2
                name: KEGG
              databaseIdentifier: R02473
            - source:
                id: 3
                name: MetaCyc
              databaseIdentifier: PANTOATE-BETA-ALANINE-LIG-RXN
          items:
            type: object
            properties:
              source:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Identifier of the source database, with `1=BRENDA`, `2=KEGG`, and `3=MetaCyc`
                  name:
                    type: string
                    description: Name of the source database.
              databaseIdentifier:
                type: string
                description: Reaction identifier in the source database.
        rxnFile:
          type: string
          format: binary
          description: RXN file of reactions atom mapping
          example: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
        type:
          type: string
          default: reaction
          description: Type of return
        updated:
          type: boolean
          example: true
          description: Update status
        updatedBy:
          type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
              description: ID of the curator
            name:
              type: string
              example: Collin
              description: Name of the curator
            orcid:
              type: string
              example: 0000-0002-2938-9940
              description: ORCID of the curator
        updatedOn:
          type: string
          example: 2020-05-11T12:43:17
          description: Date on which reaction was updated

    PathwayReaction:
      description: A representation of a reaction
      type: object
      properties:
        externalUrls:
          type: object
          properties:
            metamdb:
              type: string
              description: Link to MetAMDB reaction
              example: "https://metamdb.tu-bs.de/reaction/2"
            img:
              type: string
              description: Link to reaction image
              example: "https://metamdb.tu-bs.de/img/aam/2.svg"
        formula:
          type: string
          example: "beta-alanine + (R)-pantoate + ATP = H+ + (R)-pantothenate + diphosphate + AMP"
          description: Formula of the reaction
        href:
          type: string
          description: Link to api call
          example: "https://metamdb.tu-bs.de/api/reactions/2"
        id:
          type: integer
          format: int64
          example: 2
          description: Reaction ID
        identifiers:
          type: array
          example:
            - source:
                id: 1
                name: BRENDA
              databaseIdentifier: BR101
            - source:
                id: 2
                name: KEGG
              databaseIdentifier: R02473
            - source:
                id: 3
                name: MetaCyc
              databaseIdentifier: PANTOATE-BETA-ALANINE-LIG-RXN
          items:
            type: object
            properties:
              source:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Identifier of the source database, with `1=BRENDA`, `2=KEGG`, and `3=MetaCyc`
                  name:
                    type: string
                    description: Name of the source database.
              databaseIdentifier:
                type: string
                description: Reaction identifier in the source database.
        rxnFile:
          type: string
          format: binary
          description: RXN file of reactions atom mapping
          example: "$RXN\n\n  EC-BLAST     2\n\n  3  3\n$MOL\n{\"n\": \"(R)-pantoate\", \"i\": 10213, \"r\": \"s\", \"p\": 1}\n..."
        type:
          type: string
          default: reaction
          description: Type of return
        updated:
          type: boolean
          example: true
          description: Update status
        updatedBy:
          type: integer
          format: int64
          example: 1
          description: ID of the curator
        updatedOn:
          type: string
          example: 2020-05-11T12:43:17
          description: Date on which reaction was updated
